test: &test
  adapter: postgresql
  encoding: unicode
  database: myprojects_test
  pool: 5
  username: myapp
  password: password

development: &development
  adapter: postgresql
  encoding: unicode
  database: myprojects_development
  pool: 5
  username: myapp
  password: password
